# Generated by Django 5.2.8 on 2025-11-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('sd_card', models.BooleanField(default='False')),
                ('main_camera', models.CharField(max_length=52)),
                ('sim_card', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=10)),
                ('screen_size', models.FloatField()),
                ('battery', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('self_cam', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
