# Generated by Django 5.2.8 on 2025-11-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='color',
            field=models.CharField(default='Black', max_length=10),
        ),
        migrations.AddField(
            model_name='mobile',
            name='display',
            field=models.CharField(default='Amoled', max_length=15),
        ),
    ]
