# Generated by Django 5.2.8 on 2025-11-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mobile_color_mobile_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='screen_size',
            field=models.CharField(max_length=20),
        ),
    ]
