# Generated by Django 5.2.8 on 2025-12-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mobile_screen_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='os',
        ),
    ]
