# Generated by Django 5.2.8 on 2025-12-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_mobile_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='color',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='sd_card',
        ),
    ]
